import { beforeEach, describe, expect, it } from 'vitest'

import type {
  ExportOptions,
  ImportOptions,
  ImportResult,
  LedgerRepository,
  PurgeResult,
} from './LedgerRepository'
import type { ListQuery, Page } from './listQuery'
import type { Member, MemberId, MemberPatch, NewMember, SensitiveField } from './member'

/**
 * Shared behavioral contract for every `LedgerRepository` implementation.
 * Adapter test files import this and call it with their own factory —
 * this file also runs it against the in-memory fake below, so the contract
 * itself is always exercised even before a real storage adapter exists.
 *
 * Do not edit this file to make a new adapter pass; fix the adapter
 * (see AGENTS.md's repository-contract invariant).
 */
export function describeRepositoryContract(factory: () => LedgerRepository): void {
  describe('LedgerRepository contract', () => {
    let repo: LedgerRepository

    beforeEach(() => {
      repo = factory()
    })

    describe('create / read / update / delete', () => {
      it('creates a member and reads it back', async () => {
        const created = await repo.create(makeNewMember({ displayName: 'Ada' }))

        expect(created.id).toBeTruthy()
        expect(created.displayName).toBe('Ada')
        expect(await repo.read(created.id)).toEqual(created)
      })

      it('reads a missing member as null', async () => {
        expect(await repo.read('does-not-exist')).toBeNull()
      })

      it('updates a member and preserves unpatched fields', async () => {
        const created = await repo.create(makeNewMember({ displayName: 'Ada', role: 'organizer' }))

        const updated = await repo.update(created.id, { displayName: 'Ada Lovelace' })

        expect(updated.id).toBe(created.id)
        expect(updated.displayName).toBe('Ada Lovelace')
        expect(updated.role).toBe('organizer')
      })

      it('deletes a member; a subsequent read is null', async () => {
        const created = await repo.create(makeNewMember())

        await repo.delete(created.id)

        expect(await repo.read(created.id)).toBeNull()
      })
    })

    describe('list', () => {
      it('paginates and orders results', async () => {
        const members: Member[] = []
        for (let i = 0; i < 5; i++) {
          members.push(await repo.create(makeNewMember({ displayName: `Member ${i}` })))
        }

        const firstPage = await repo.list({ limit: 2, orderBy: 'createdAt', orderDirection: 'asc' })
        expect(firstPage.items.map((m) => m.id)).toEqual([members[0]!.id, members[1]!.id])
        expect(firstPage.nextCursor).toBe(members[1]!.id)

        const secondPage = await repo.list({
          limit: 2,
          cursor: firstPage.nextCursor,
          orderBy: 'createdAt',
          orderDirection: 'asc',
        })
        expect(secondPage.items.map((m) => m.id)).toEqual([members[2]!.id, members[3]!.id])

        const lastPage = await repo.list({
          limit: 2,
          cursor: secondPage.nextCursor,
          orderBy: 'createdAt',
          orderDirection: 'asc',
        })
        expect(lastPage.items.map((m) => m.id)).toEqual([members[4]!.id])
        expect(lastPage.nextCursor).toBeNull()
      })

      it('filters on non-sensitive fields (expiresBefore/expiresAfter)', async () => {
        const soonExpiring = await repo.create(
          makeNewMember({ expiresAt: new Date('2026-01-01T00:00:00.000Z') }),
        )
        const laterExpiring = await repo.create(
          makeNewMember({ expiresAt: new Date('2027-01-01T00:00:00.000Z') }),
        )
        await repo.create(makeNewMember({ expiresAt: null }))

        const before = await repo.list({
          filter: { expiresBefore: new Date('2026-06-01T00:00:00.000Z') },
        })
        expect(before.items.map((m) => m.id)).toEqual([soonExpiring.id])

        const after = await repo.list({
          filter: { expiresAfter: new Date('2026-06-01T00:00:00.000Z') },
        })
        expect(after.items.map((m) => m.id)).toEqual([laterExpiring.id])
      })
    })

    describe('purgeExpired', () => {
      it('removes only members whose expiresAt is at or before `now`', async () => {
        const now = new Date('2026-01-01T00:00:00.000Z')
        const alreadyExpired = await repo.create(
          makeNewMember({ expiresAt: new Date('2025-12-31T00:00:00.000Z') }),
        )
        const dueNow = await repo.create(makeNewMember({ expiresAt: now }))
        const notYetExpired = await repo.create(
          makeNewMember({ expiresAt: new Date('2026-06-01T00:00:00.000Z') }),
        )
        const neverExpires = await repo.create(makeNewMember({ expiresAt: null }))

        const result = await repo.purgeExpired(now)

        expect(result.purged).toBe(2)
        expect(await repo.read(alreadyExpired.id)).toBeNull()
        expect(await repo.read(dueNow.id)).toBeNull()
        expect(await repo.read(notYetExpired.id)).not.toBeNull()
        expect(await repo.read(neverExpires.id)).not.toBeNull()
      })
    })

    describe('findByBlindIndex', () => {
      it('matches a normalized value regardless of case or surrounding whitespace', async () => {
        const match = await repo.create(makeNewMember({ displayName: '  Ada Lovelace  ' }))
        await repo.create(makeNewMember({ displayName: 'Grace Hopper' }))

        const results = await repo.findByBlindIndex('displayName', 'ada lovelace')

        expect(results.map((m) => m.id)).toEqual([match.id])
      })

      it('matches nothing when no value normalizes the same way', async () => {
        await repo.create(makeNewMember({ displayName: 'Ada Lovelace' }))

        expect(await repo.findByBlindIndex('displayName', 'nobody here')).toEqual([])
      })
    })

    describe('export / import', () => {
      it('round-trips a bundle into a fresh repository', async () => {
        await repo.create(makeNewMember({ displayName: 'Ada Lovelace', email: 'ada@example.org' }))
        await repo.create(makeNewMember({ displayName: 'Grace Hopper', role: 'organizer' }))

        const bundle = await repo.exportEncrypted({ passphrase: 'correct-horse-battery-staple' })

        const fresh = factory()
        const { imported } = await fresh.importEncrypted(bundle, {
          passphrase: 'correct-horse-battery-staple',
        })

        expect(imported).toBe(2)
        const { items } = await fresh.list({ limit: 10 })
        expect(items.map((m) => m.displayName).sort()).toEqual(['Ada Lovelace', 'Grace Hopper'])
      })
    })
  })
}

function makeNewMember(overrides: Partial<NewMember> = {}): NewMember {
  return {
    displayName: 'Test Member',
    email: null,
    phone: null,
    role: null,
    notes: null,
    expiresAt: null,
    ...overrides,
  }
}

/**
 * Test-only fake. It is not encrypted — a real adapter must compose
 * libsodium/age/WebCrypto/OpenBao transit per AGENTS.md rule 1. It exists
 * purely so this contract has something to run against before PGlite or
 * Postgres adapters land.
 */
class InMemoryRepository implements LedgerRepository {
  private readonly members = new Map<MemberId, Member>()
  private readonly sequence = new Map<MemberId, number>()
  private nextId = 1
  private nextSeq = 0

  async create(input: NewMember): Promise<Member> {
    const id = String(this.nextId++)
    const now = new Date()
    const member: Member = { ...input, id, createdAt: now, updatedAt: now }
    this.members.set(id, member)
    this.sequence.set(id, this.nextSeq++)
    return { ...member }
  }

  async read(id: MemberId): Promise<Member | null> {
    const member = this.members.get(id)
    return member ? { ...member } : null
  }

  async update(id: MemberId, patch: MemberPatch): Promise<Member> {
    const existing = this.members.get(id)
    if (!existing) {
      throw new Error(`Member not found: ${id}`)
    }
    const updated: Member = { ...existing, ...patch, updatedAt: new Date() }
    this.members.set(id, updated)
    return { ...updated }
  }

  async delete(id: MemberId): Promise<void> {
    this.members.delete(id)
    this.sequence.delete(id)
  }

  async list(query: ListQuery = {}): Promise<Page<Member>> {
    const {
      limit = 20,
      cursor = null,
      orderBy = 'createdAt',
      orderDirection = 'asc',
      filter,
    } = query

    let items = [...this.members.values()]

    if (filter?.expiresBefore) {
      const before = filter.expiresBefore
      items = items.filter((m) => m.expiresAt !== null && m.expiresAt < before)
    }
    if (filter?.expiresAfter) {
      const after = filter.expiresAfter
      items = items.filter((m) => m.expiresAt !== null && m.expiresAt > after)
    }

    items.sort((a, b) => {
      const aTime = a[orderBy]?.getTime() ?? -Infinity
      const bTime = b[orderBy]?.getTime() ?? -Infinity
      if (aTime !== bTime) {
        return orderDirection === 'asc' ? aTime - bTime : bTime - aTime
      }
      const aSeq = this.sequence.get(a.id) ?? 0
      const bSeq = this.sequence.get(b.id) ?? 0
      return orderDirection === 'asc' ? aSeq - bSeq : bSeq - aSeq
    })

    const startIndex = cursor ? items.findIndex((m) => m.id === cursor) + 1 : 0
    const page = items.slice(startIndex, startIndex + limit)
    const nextCursor = startIndex + page.length < items.length ? (page.at(-1)?.id ?? null) : null

    return { items: page.map((m) => ({ ...m })), nextCursor }
  }

  async findByBlindIndex(field: SensitiveField, value: string): Promise<Member[]> {
    const target = normalize(value)
    return [...this.members.values()]
      .filter((m) => normalize(String(m[field] ?? '')) === target)
      .map((m) => ({ ...m }))
  }

  async purgeExpired(now: Date = new Date()): Promise<PurgeResult> {
    let purged = 0
    for (const [id, member] of this.members) {
      if (member.expiresAt !== null && member.expiresAt <= now) {
        this.members.delete(id)
        this.sequence.delete(id)
        purged++
      }
    }
    return { purged }
  }

  async exportEncrypted(opts: ExportOptions): Promise<Uint8Array> {
    void opts
    const json = JSON.stringify([...this.members.values()])
    return new TextEncoder().encode(json)
  }

  async importEncrypted(bundle: Uint8Array, opts: ImportOptions): Promise<ImportResult> {
    void opts
    const json = new TextDecoder().decode(bundle)
    const members = JSON.parse(json, reviveDates) as Member[]
    for (const member of members) {
      this.members.set(member.id, member)
      this.sequence.set(member.id, this.nextSeq++)
    }
    return { imported: members.length }
  }
}

const DATE_FIELDS = new Set(['createdAt', 'updatedAt', 'expiresAt'])

function reviveDates(key: string, value: unknown): unknown {
  return DATE_FIELDS.has(key) && typeof value === 'string' ? new Date(value) : value
}

function normalize(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, ' ')
}

describeRepositoryContract(() => new InMemoryRepository())
